selection:
  # Option 1: use a Python selection function
  file: event_selection.py
  function: select_pt

  # Option 2: use an inline Python filter expression
  # filter: "ak.any(np.sqrt(Jet.px*Jet.px + Jet.py*Jet.py) > 90, axis=1)"

variables:
  Jet:
    - pt: "np.sqrt(px*px + py*py)"
    - mass
    - charge
    - goodnessOfPID
  Muon:
    - charge
  Electron:
    - mass
  Photon: