selection:
  # Option 1: use a Python selection function
  script:
    file_name: event_selection.py
    function: select_pt

  # Option 2: use an inline Python filter expression
  # filter: "ak.any(np.sqrt(Jet.px*Jet.px + Jet.py*Jet.py) > 90, axis=1)"

additional_fields: 
  -  file_name: new_collections.py
     function: particle_collections

variables:
  Jet:
    - pt: "np.sqrt(px*px + py*py)"
    - mass
    - charge
    - goodnessOfPID
  Muon:
    - charge
  Electron:
    - mass
  Photon: